---
deployment:
  tasks:
    - export DEPLOYPATH=/home/avtocent/public_html
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/cp style.css $DEPLOYPATH/
    - /bin/cp script.js $DEPLOYPATH/
    - /bin/cp vehicle-details.html $DEPLOYPATH/
    - /bin/cp -R images $DEPLOYPATH
